name: PHP Syntax Check

on: [push, pull_request]

jobs:
  syntax-checker:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php: [ '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2' ]
    name: PHP ${{ matrix.php }} Syntax Check
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Setup PHP
        id: SetupPHP
        uses: nanasess/setup-php@master
        with:
          php-version: ${{ matrix.php }}
      - run: php ./.github/check-php-syntax.php ./